---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mqtt-publish
spec:
  params:
    - name: broker-hostname
      description: |
        Hostname of the broker with port, eg tcp://123.41.123.4:1883
    - name: topic
      description: topic to publish on
      default: "/build"
    - name: payload-file
      description: Name of the file to read that contains the payload
    - name: retained-pub
      description: Should the publish message be marked as retained?
      default: true
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: workspace
      description: |
        A workspace that contain payload-file
      mountPath: /data
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
  steps:
    - name: post-to-slack
      image: ampretia/tekton-mqtt:1.0
      env:
        # keep slack message injected in an env var to let YAML manage the quote for us
        - name: BROKER
          value: $(params.broker-hostname)
        - name: TOPIC
          value: $(params.topic)
        - name: PAYLOAD
          value: $(params.payload-file)
        - name: RETAINED
          value: $(params.retained-pub)
      command: ["node", "index.js"]
      workingDir: /usr/src/app
