apiVersion: v1
kind: Service
metadata:
  namespace: notifications
  name: mosquitto
  labels:
    app: mqtt
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  selector:
    app: mqtt
