apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto.conf
  namespace: notifications
  labels:
    app: mqtt  
data:
  mosquitto.conf: |    
    log_dest stdout
    listener 1883
    protocol mqtt
    # set up websockets
    listener 9003
    protocol websockets
