---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: triggertemplate-git-trigger
spec:
  params:
    - name: trigger-name 
      description: triggername
    - name: pipeline-debug
      default: "0"
    - name: broker-hostname
      description: MQTT broker 
    - name: topic
      description: Full topic name         
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.trigger-name)-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.trigger-name)-$(uid)
      spec:
        pipelineRef:
          name: my-pipeline
        params:
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: trigger-name
            value: $(params.trigger-name)
          - name: broker-hostname
            value: $(params.broker-hostname)
          - name: topic
            value: $(params.topic)                    
        workspaces:
          - name: code
            subPath: code
            persistentVolumeClaim:
              claimName: $(params.trigger-name)-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-manual
spec:
  params:
    - name: trigger-name
      value: "manual-trigger"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-github-pr
spec:
  params:
    - name: trigger-name
      value: "github-pullrequest"
---
# This listener is triggered when a PR is created or updated
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-github-pr
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-github-pr
      template:
        name: triggertemplate-git-trigger
---
# Manual trigger of the build - will run off main branch
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-manual
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-manual
      template:
        name: triggertemplate-git-trigger