---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: triggertemplate-git-trigger
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
      default: " "
    - name: repository
      description: The git repo
      default: " "
    - name: branch
      description: the branch for the git repo
    - name: revision
      description: the commit id/sha for the clone action
      default: " "
    - name: pr-repository
      description: The source git repo for the PullRequest
      default: " "
    - name: pr-branch
      description: The source branch for the PullRequest
      default: " "
    - name: pr-revision
      description: the commit id/sha for the PullRequest
      default: " "
    - name: triggerName
      default: "git-pr-process"
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(params.triggerName)-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.triggerName)-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-revision
            value: $(params.pr-revision)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: triggerName
            value: $(params.triggerName)
        workspaces:
          - name: code
            subPath: code
            persistentVolumeClaim:
              claimName: $(params.triggerName)-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-manual
spec:
  params:
    - name: repository
      value: "https://github.ibm.com/ibp/marvin-container"
    - name: branch
      value: "main"
    - name: triggerName
      value: manual-trigger
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-github-pr
spec:
  params:
    - name: repository
      value: "$(event.pull_request.base.repo.clone_url)"
    - name: branch
      value: "$(event.pull_request.base.ref)"
    - name: pr-repository
      value: "$(event.pull_request.head.repo.clone_url)"
    - name: pr-branch
      value: "$(event.pull_request.head.ref)"
    - name: pr-revision
      value: "$(event.pull_request.head.sha)"
    - name: triggerName
      value: "github-pullrequest"
---
# This listener is triggered when a PR is created or updated
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-github-pr
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-github-pr
      template:
        name: triggertemplate-git-trigger
---
# Manual trigger of the build - will run off main branch
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-manual
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-manual
      template:
        name: triggertemplate-git-trigger